import { ArrowRight, Check, Clock3, FileSpreadsheet, KeyRound, Search, ShieldCheck, ShoppingBag, Tags, Users } from 'lucide-react'
import './App.css'

const features=[
 [Tags,'แท็ก 5 ตัว ค้นหาได้ทันที','ทุกไอดีมีแท็กเฉพาะ เช่น #23DX5 ใช้ค้นหาและคุยกับลูกค้าได้โดยไม่สับสน'],
 [FileSpreadsheet,'ย้ายจาก Spreadsheet ได้ง่าย','อัปโหลด CSV จับคู่คอลัมน์ ดูตัวอย่าง และตรวจข้อผิดพลาดก่อนนำเข้าจริง'],
 [Clock3,'จองและขายโดยไม่ชนกัน','ล็อกรายการในจังหวะขาย ป้องกันพนักงานสองคนขายไอดีเดียวกัน'],
 [ShieldCheck,'ข้อมูลสำคัญแยกและเข้ารหัส','Credentials ไม่ปนในข้อมูลปกติ เปิดดูได้เมื่อมีสิทธิ์ 2FA และยืนยันตัวตนล่าสุด'],
 [Users,'แบ่งสิทธิ์เจ้าของและพนักงาน','กำหนดว่าใครจัดการสต็อก ดูต้นทุน เปิด credentials หรือ export ข้อมูลได้'],
 [ShoppingBag,'เห็นสุขภาพร้านในหน้าเดียว','ติดตามพร้อมขาย ถูกจอง ยอดขาย กำไร มูลค่าสต็อก และกิจกรรมล่าสุด'],
] as const

function App(){return <div className="site"><header className="container nav"><a className="logo" href="#top"><img src="/mascot/gammy-hello.png" alt="Gammy"/><span>Gamory<span>ID</span></span></a><nav className="links"><a href="#features">ฟีเจอร์</a><a href="#workflow">วิธีใช้งาน</a><a href="#pricing">แพ็กเกจ</a><a className="btn" href="http://localhost:5173">เข้าสู่ระบบ</a><a className="btn orange" href="#pricing">เริ่มใช้ฟรี</a></nav></header>
<main id="top"><section className="container hero"><div><span className="badge"><ShieldCheck size={15}/>ระบบจัดการสต็อกสำหรับร้านดิจิทัล</span><h1>หาไอดีให้เจอ<br/><em>ปิดการขายให้ไว</em></h1><p>GamoryID รวมสต็อก การจอง ลูกค้า และประวัติการขายไว้ในที่เดียว ให้ทีมร้านทำงานกับข้อมูลจำนวนมากได้ง่ายขึ้น</p><div className="hero-actions"><a className="btn orange" href="#pricing">ทดลองใช้ฟรี 30 วัน <ArrowRight size={17}/></a><a className="btn" href="#features">ดูวิธีทำงาน</a></div><p className="small-note">ไม่ต้องใส่บัตรเครดิต · ส่งออกข้อมูลของร้านได้</p></div><div className="product-shot" aria-label="ตัวอย่างหน้าระบบ GamoryID"><div className="mock"><div className="mock-top"><span className="dot"/><span className="dot"/><span className="dot"/></div><div className="mock-body"><div className="mock-side"><div className="mock-line active"/><div className="mock-line"/><div className="mock-line"/><div className="mock-line"/></div><div className="mock-main"><div className="mock-title"/><div className="mock-kpis"><i/><i/><i/></div><div className="mock-table">{[1,2,3,4,5].map(i=><div className="mock-row" key={i}><b/><i/><i/><i/></div>)}</div></div></div></div><img className="hero-mascot" src="/mascot/gammy-secure.png" alt="Gammy ดูแลความปลอดภัย"/></div></section>
<section className="trust"><div className="container"><div className="trust-item"><KeyRound size={18}/>Credentials เข้ารหัส</div><div className="trust-item"><Search size={18}/>Exact tag search</div><div className="trust-item"><ShieldCheck size={18}/>สิทธิ์แยกตามคน</div><div className="trust-item"><FileSpreadsheet size={18}/>นำเข้าและส่งออก CSV</div></div></section>
<section className="section container" id="features"><div className="section-head"><span className="kicker">ทำงานไวขึ้นทุกวัน</span><h2>สร้างมาเพื่อเวิร์กโฟลว์ของร้านจริง</h2><p>พื้นที่ทำงานที่ชัดเจนสำหรับงานซ้ำทุกวัน ตั้งแต่นำเข้าหลายร้อยรายการ จนถึงค้นหาไอดีให้ลูกค้าในไม่กี่วินาที</p></div><div className="features">{features.map(([Icon,title,text])=><article className="feature" key={title}><div className="feature-icon"><Icon size={21}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="section tint" id="workflow"><div className="container"><div className="section-head"><span className="kicker">จากไฟล์ สู่ยอดขาย</span><h2>เริ่มใช้ได้ใน 3 ขั้นตอน</h2></div><div className="steps"><Step n="01" title="นำเข้าสต็อก" text="อัปโหลด CSV จับคู่คอลัมน์ ตรวจข้อมูล แล้วปล่อยให้ระบบประมวลผลเบื้องหลัง"/><Step n="02" title="หาและจอง" text="ค้นจากแท็ก 5 ตัว ชื่อ แรงก์ หรือเซิร์ฟเวอร์ แล้วจองให้ลูกค้าพร้อมเวลาหมดอายุ"/><Step n="03" title="บันทึกขาย" text="เก็บลูกค้า ราคาขาย ต้นทุน กำไร และผู้ทำรายการในประวัติที่ตรวจสอบย้อนหลังได้"/></div></div></section>
<section className="section container" id="pricing"><div className="section-head"><span className="kicker">เริ่มเล็ก ขยายตามร้าน</span><h2>แพ็กเกจตรงไปตรงมา</h2><p>ทดลองใช้ฟรี 30 วัน หลังจากนั้นเลือกแพ็กเกจตามจำนวนสต็อกและทีมของคุณ</p></div><div className="price-wrap"><Price name="Starter" amount="299" inventory="1,000" members="3"/><Price name="Growth" amount="699" inventory="5,000" members="8" recommended/></div></section>
<section className="container cta"><div><h2>พร้อมจัดร้านให้เป็นระบบหรือยัง?</h2><p>เริ่มนำเข้าสต็อก ค้นหา และบันทึกขายได้วันนี้</p><div className="hero-actions"><a href="mailto:hello@gamoryid.local" className="btn orange">ขอทดลองใช้งาน <ArrowRight size={17}/></a></div></div><img src="/mascot/gammy-hello.png" alt="Gammy กล่าวต้อนรับ"/></section></main>
<footer className="footer"><div className="container"><strong>GamoryID — ระบบจัดการสินค้าดิจิทัลสำหรับร้านค้า</strong><span>GamoryID ไม่มีความเกี่ยวข้องหรือได้รับการรับรองจากผู้พัฒนาเกมรายใด</span></div></footer></div>}
function Step({n,title,text}:{n:string;title:string;text:string}){return <article className="step"><span className="step-num">STEP {n}</span><h3>{title}</h3><p>{text}</p></article>}
function Price({name,amount,inventory,members,recommended=false}:{name:string;amount:string;inventory:string;members:string;recommended?:boolean}){return <article className={`price ${recommended?'recommended':''}`}>{recommended&&<span className="price-label">เหมาะกับร้านที่กำลังโต</span>}<h3>{name}</h3><div className="amount">฿{amount} <small>/ 30 วัน</small></div><ul><li><Check size={17}/>สต็อกพร้อมขายสูงสุด {inventory} รายการ</li><li><Check size={17}/>สมาชิกในร้าน {members} คน</li><li><Check size={17}/>นำเข้า CSV และ export ข้อมูล</li><li><Check size={17}/>ประวัติกิจกรรมและ 2FA</li></ul><a className={`btn ${recommended?'blue':''}`} href="mailto:hello@gamoryid.local">เริ่มทดลองใช้ฟรี</a></article>}
export default App
