import type { InventoryItem } from "../../types/models";

export const DEFAULT_COPY_FOOTER =
  "สนใจรายละเอียดเพิ่มเติมสามารถสอบถามได้ทางช่องทางติดต่อของร้าน";

export const initialInventoryItems: InventoryItem[] = [
  {
    id: 1,
    tag: "#23DX5",
    title: "รายละเอียดไอดี Reaver Collection",
    riotId: "Gammy#TH01",
    username: "gammy.ops01",
    email: "gammy.ops01@mail.test",
    rank: "Ascendant 2",
    level: 238,
    skins: 67,
    cost: 6200,
    price: 8900,
    status: "available",
    updated: "8 นาทีที่แล้ว",
    hasCredentials: true,
    media: [],
  },
  {
    id: 2,
    tag: "#8KM4R",
    title: "รายละเอียดไอดี Prime Collection",
    riotId: "Nova#TH02",
    username: "nova.trade02",
    email: "nova.trade02@mail.test",
    rank: "Diamond 3",
    level: 191,
    skins: 49,
    cost: 4400,
    price: 6900,
    status: "reserved",
    updated: "24 นาทีที่แล้ว",
    hasCredentials: true,
    media: [],
  },
  {
    id: 3,
    tag: "#Q7N2P",
    title: "รายละเอียดไอดี Champions",
    riotId: "Vega#TH03",
    username: "vega.market03",
    email: "vega.market03@mail.test",
    rank: "Immortal 1",
    level: 306,
    skins: 82,
    cost: 9900,
    price: 13900,
    status: "available",
    updated: "42 นาทีที่แล้ว",
    hasCredentials: true,
    media: [],
  },
  {
    id: 4,
    tag: "#4WT9C",
    title: "รายละเอียดไอดี Kuronami",
    riotId: "Sora#TH04",
    username: "sora.store04",
    email: "sora.store04@mail.test",
    rank: "Platinum 2",
    level: 144,
    skins: 35,
    cost: 2700,
    price: 4500,
    status: "available",
    updated: "1 ชม.ที่แล้ว",
    media: [],
  },
  {
    id: 5,
    tag: "#M6J3X",
    title: "รายละเอียดไอดี RGX",
    riotId: "Milo#TH05",
    username: "milo.trade05",
    email: "milo.trade05@mail.test",
    rank: "Diamond 1",
    level: 217,
    skins: 55,
    cost: 5200,
    price: 7600,
    status: "sold",
    updated: "2 ชม.ที่แล้ว",
    media: [],
  },
  {
    id: 6,
    tag: "#9RA5K",
    title: "รายละเอียดไอดี Prelude",
    riotId: "Rin#TH06",
    username: "rin.market06",
    email: "rin.market06@mail.test",
    rank: "Ascendant 1",
    level: 262,
    skins: 71,
    cost: 6800,
    price: 9600,
    status: "available",
    updated: "3 ชม.ที่แล้ว",
    media: [],
  },
  {
    id: 7,
    tag: "#C3Y8N",
    title: "รายละเอียดไอดี Gaia",
    riotId: "Aster#TH07",
    username: "aster.store07",
    email: "aster.store07@mail.test",
    rank: "Gold 3",
    level: 128,
    skins: 42,
    cost: 3100,
    price: 4900,
    status: "reserved",
    updated: "เมื่อวาน",
    media: [],
  },
  {
    id: 8,
    tag: "#H5P7D",
    title: "รายละเอียดไอดี Neo Frontier",
    riotId: "Kai#TH08",
    username: "kai.trade08",
    email: "kai.trade08@mail.test",
    rank: "Diamond 2",
    level: 174,
    skins: 38,
    cost: 3900,
    price: 6100,
    status: "available",
    updated: "เมื่อวาน",
    media: [],
  },
];
